// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_charactor from "./routes/api/charactor.ts";
import * as $api_winrateData from "./routes/api/winrateData.ts";
import * as $index from "./routes/index.tsx";
import * as $ChartView from "./islands/ChartView.tsx";
import * as $Filters from "./islands/Filters.tsx";
import * as $TableView from "./islands/TableView.tsx";
import * as $chart from "./islands/chart.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/charactor.ts": $api_charactor,
    "./routes/api/winrateData.ts": $api_winrateData,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChartView.tsx": $ChartView,
    "./islands/Filters.tsx": $Filters,
    "./islands/TableView.tsx": $TableView,
    "./islands/chart.tsx": $chart,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
