name: Create Data
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  create_data:
    name: Create Data
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Japanese font.
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: fonts-noto
          version: 1.0
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno deps
        id: cache_dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: cache-${{ hashFiles('deno.lock') }}
          restore-keys: cache-
      - name: Install Deps
        run: deno task cache-create-data-deps
      - name: Create data
        run: deno task create_data
        env:
          DENO_KV_REMOTE_URL: ${{ secrets.DENO_KV_REMOTE_URL }}
          DENO_KV_ACCESS_TOKEN: ${{ secrets.DENO_KV_ACCESS_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: Upload Snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ github.sha }}
          path: snapshots
