name: Deploy
on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install Deps
        run: deno task cache-fresh-deps
      - name: Cache Deno deps
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: cache-${{ hashFiles('deno.lock') }}
          restore-keys: cache-
      - name: Create env file
        run: |
          touch .env
          cp .env.example .env
      - name: Build step
        run: "deno task build"
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "sf6-winrate-viewer"
          entrypoint: "main.ts"
          root: "."
